DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS company;
CREATE TABLE employee (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  age INT NOT NULL,
  gender VARCHAR(10) DEFAULT NULL,
  company_id INT Not NULL
);

INSERT INTO EMPLOYEE(ID,NAME,AGE,GERDER,COMPANY_ID) values (1,"JENKIN",18,"MALE",1);
 CREATE TABLE company (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   name VARCHAR(100) NOT NULL
 );
INSERT INTO company(ID,NAME) values (1,"JENKIN");